CI/CD
kestra-io/kestra.io pull request #125
Opened 2023-02-01 19:52 UTC by Skraye

2023-02-02 07:15 UTC, loicmathieu reviewed
I added a bunch a suggestions.

In addition:
- Try to keep the GitHub and GitLab wording as close as possible
- Explain a little more Terraform, at least introduce each example
- Add a Warning box to clearly say that teamplates MUST be deployed before flows
- For Terraform, also add an example with a template and use a depends on to make the template created before the flow

Reading the GitHub action, I wonder if the parameter `resource` should be renamed to `resourceType` as we talk about the type of the resource to validate / deploy not the resource itself.

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/github-action/README.md
> +Kestra offer 2 `Actions` to create a CI/CD inside GitHub.
```suggestion
Kestra offer 2 `Actions` to create a CI/CD pipeline within a GitHub repository.
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/github-action/README.md
> +[Kestra Validate Action]() - Validate your flows and your templates before deploying anything.
```suggestion
[Kestra Validate Action]() - Validates your flows and your templates.
```

Also, why did you add an empty link ?

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/github-action/README.md
> +[Kestra Deploy Action]() - Deploy your flows and your templates to your Kestra server.
```suggestion
[Kestra Deploy Action]() - Deploys your flows and your templates to your Kestra server.
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/github-action/README.md
> +Here is an example of a `Workflow` using `Kestra Actions` that validate all `Flows` and `Templates` before deploying them.
```suggestion
Here is an example of a GitHub workflow using the Kestra actions to validate all `Flows` and `Templates` before deploying them.
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/github-action/README.md
> +      # Validate all templates within the client
```suggestion
      # Validate all templates with the client
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/github-action/README.md
> +      # Can only deploy in one namespace at once
```suggestion
      # We can only deploy in one namespace at once,
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/github-action/README.md
> +      # so we have 2 differents step for our two namespaces io.kestra and io.kestra.dev
```suggestion
      # so we have 2 different steps for our two namespaces io.kestra and io.kestra.dev
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/github-action/README.md
> +      - name: Deploy prod flows
```suggestion
      - name: Deploy flows in io.kestra
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/github-action/README.md
> +        description: Deploy flow in the io.kestra namespace
```suggestion
        description: Deploy flows in the io.kestra namespace
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/github-action/README.md
> +        description: Deploy flow in the io.kestra.dev namespace
```suggestion
        description: Deploy flows in the io.kestra.dev namespace
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/gitlab/README.md
> +GitLab integrate a solution call [GitLAb CI/CD](https://docs.gitlab.com/ee/ci/) that allow you to
```suggestion
GitLab integrates a solution called [GitLab CI/CD](https://docs.gitlab.com/ee/ci/) that allows you to
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/gitlab/README.md
> +define pipelines in `YAML` files to automate tests, compilation or even deployment for your
```suggestion
define pipelines in `YAML` files to automate tests, compilation or even deploy your
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/gitlab/README.md
> +Here is an example of a GitLab CI pipeline. We define 3 stages, `test` where we validate our flow,
```suggestion
Here is an example of a GitLab CI pipeline. We define 3 stages, `test` where we validate our flows,
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/gitlab/README.md
> +`deploy-template` where we deploy our `templates` before our `flows`, to avoid running before their
```suggestion
`deploy-template` where we deploy our `templates` before our `flows`, to avoid running flows before their
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/gitlab/README.md
> +  # Validate our template within the client
```suggestion
  # Validate our templates with the client
```

2023-02-02 07:15 UTC, loicmathieu commented on docs/developer-guide/cicd/terraform/README.md
> +More details can be [here](https://registry.terraform.io/providers/kestra-io/kestra/latest/docs).
```suggestion
More details can be foud [here](https://registry.terraform.io/providers/kestra-io/kestra/latest/docs).
```

2023-02-08 09:31 UTC, tanay1337 requested changes

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +GitHub integrates a solution called [GitHub Actions](https://github.com/features/actions) that allow you
```suggestion
GitHub integrates a solution called [GitHub Actions](https://github.com/features/actions), allowing you to create CI/CD pipelines easily.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +to create CI/CD pipelines easily.
```suggestion

```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +Those pipelines are called `Workflows` and are build from `Actions` which
```suggestion
These pipelines are called Workflows and are built with Actions, which perform complex tasks with a small amount of code.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +performs complex tasks with small amount of codes.
```suggestion

```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +Kestra offer 2 `Actions` to create a CI/CD pipeline within a GitHub repository.
```suggestion
Kestra offers two Actions to create a CI/CD pipeline within a GitHub repository.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +[Kestra Validate Action](https://github.com/kestra-io/validate-action/releases) - Validate your flows and your templates before deploying anything.
```suggestion
* [Kestra Validate Action](https://github.com/kestra-io/validate-action/releases) - Validate your flows and templates before deploying anything.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +
```suggestion
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +[Kestra Deploy Action](https://github.com/kestra-io/deploy-action/releases) - Deploy your flows and your templates to your Kestra server.
```suggestion
* [Kestra Deploy Action](https://github.com/kestra-io/deploy-action/releases) - Deploy your flows and templates to your Kestra server.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +Here is an example of a `Workflow` using `Kestra Actions` that validate all `Flows` and `Templates` before deploying them.
+1

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +`Flows` should always be deployed before `Templates`, to avoid flows running before their templates are created.
```suggestion
Flows should always be deployed before Templates to avoid flows running before their templates are created.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +      # Validate all templates within the client
+1

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +      # Validate all flows with the server
Same as Loïc's comment above.

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +      # Can only deploy in one namespace at once
+1

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +      # so we have 2 differents step for our two namespaces io.kestra and io.kestra.dev
+1

One more change:
2 -> two

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +      - name: Deploy prod flows
+1

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +        description: Deploy flow in the io.kestra namespace
+1

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/github-action/README.md
> +        description: Deploy flow in the io.kestra.dev namespace
+1

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/gitlab/README.md
> +GitLab integrates a solution called [GitLAb CI/CD](https://docs.gitlab.com/ee/ci/) that allow you to
```suggestion
GitLab integrates a solution called [GitLAb CI/CD](https://docs.gitlab.com/ee/ci/) that allows you to define pipelines in YAML files to automate tests, compilation, or even deployment for your applications.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/gitlab/README.md
> +define pipelines in `YAML` files to automate tests, compilation, or even deploy for your
```suggestion
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/gitlab/README.md
> +Applications.
```suggestion
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/gitlab/README.md
> +Here is an example of a GitLab CI pipeline. We define 3 stages, `test` where we validate our flows,
```suggestion
Here is an example of a GitLab CI pipeline. We define three stages:
*`test`, where we validate our flows 
*`deploy-template`, where we deploy our `templates`
* stage `deploy-flow`, where we deploy our flows.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/gitlab/README.md
> +`deploy-template` where we deploy our `templates` and finally the stage `deploy-flow` where we deploy our flows.
```suggestion
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/gitlab/README.md
> +`Flows` should always be deployed before `Templates`, to avoid flows running before their templates are created.
```suggestion
Flows should always be deployed before Templates to avoid flows running before their templates are created.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/terraform/README.md
> +You can use the [Official Kestra Provider](https://registry.terraform.io/providers/kestra-io/kestra/latest) to manage
```suggestion
You can use the [Official Kestra Provider](https://registry.terraform.io/providers/kestra-io/kestra/latest) to manage every available resource in Kestra.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/terraform/README.md
> +eevery available resource in Kestra.
```suggestion
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/terraform/README.md
> +`Flows` should always be deployed before `Templates`, to avoid flows running before their templates are created.
```suggestion
Flows should always be deployed before Templates to avoid flows running before their templates are created.
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/terraform/README.md
> +First, you need to create a `provider.tf` or `main.tf` file with the following content, to configure the provider:
```suggestion
First, you need to create a `provider.tf` or `main.tf` file with the following content to configure the provider:
```

2023-02-08 09:31 UTC, tanay1337 commented on docs/developer-guide/cicd/terraform/README.md
> +  # mandatory, the url to kestra
```suggestion
  # mandatory, the URL for kestra
```

2023-02-08 10:12 UTC, merged